version: '3.8'

networks:
  default:
    external: true
    name: mainNetwork


services:
  nginx:
    image: nginx:stable
    container_name: Gym-NGINX
    ports:
      - "9400:80"
    volumes:
      - .:/var/www/gym
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: Gym-PHP
    volumes:
      - .:/var/www/gym
      - ./docker/php/www.conf:/usr/local/etc/php/conf.d/www.conf
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: always